const data = [
  {
    id: 1,
    name: "JS-Algorithms",
    image: "JS-Algorithms",
    url: "https://github.com/huseyin-aln/javascriptAlgorithms",
    source: "https://github.com/huseyin-aln/javascriptAlgorithms",
    tool: "javascript",
  },
  {
    id: 2,
    name: "Blog App",
    image: "Blog App",
    url: "https://django-blog-app.netlify.app",
    source: "https://github.com/huseyin-aln/Capstone-Blog-App-RP",
    tool: "react",
  },
  {
    id: 3,
    name: "Fire-Blog App",
    image: "Fire-Blog App",
    url: "https://fireblog-app-rp.netlify.app/",
    source: "https://github.com/huseyin-aln/FireBlog-App-RP",
    tool: "react",
  },
  {
    id: 4,
    name: "Coronavirus_Dashboard_App",
    image: "Coronavirus_Dashboard_App",
    url: "coronavirus-dashboard-app.netlify.app/",
    source: "https://github.com/huseyin-aln/Coronavirus_Dashboard_App",
    tool: "react",
  },
  {
    id: 5,
    name: "Fire-Contant-App-RP",
    image: "Fire-Contant-App-RP",
    url: "fire-contact-rp.netlify.app/",
    source: "https://github.com/huseyin-aln/Fire-Contant-App-RP",
    tool: "react",
  },
  {
    id: 6,
    name: "Recipe-App-RP",
    image: "Recipe-App-RP",
    url: "recipeapp-rp.netlify.app/",
    source: "https://github.com/huseyin-aln/Recipe-App-RP",
    tool: "react",
  },
  {
    id: 7,
    name: "Movie-App-RP",
    image: "Movie-App-RP",
    url: "movie-app-rp.netlify.app/",
    source: "https://github.com/huseyin-aln/Movie-App-RP",
    tool: "react",
  },
  {
    id: 8,
    name: "Weather-App-RP",
    image: "Weather-App-RP",
    url: "weatherapp-rp.netlify.app/",
    source: "https://github.com/huseyin-aln/Weather-App-RP",
    tool: "react",
  },
  {
    id: 9,
    name: "Tour-Places-RP",
    image: "Tour-Places-RP",
    url: "tour-places-rp.netlify.app",
    source: "https://github.com/huseyin-aln/Tour-Places-RP",
    tool: "react",
  },
  {
    id: 10,
    name: "projeTourWithFetch-RP",
    image: "projeTourWithFetch-RP",
    url: "projetourwithfetch-rp.netlify.app/",
    source: "https://github.com/huseyin-aln/projeTourWithFetch-RP",
    tool: "react",
  },
  {
    id: 11,
    name: "Sass-Website",
    image: "Sass-Website",
    url: "huseyin-aln.github.io/005-Sass-Website/",
    source: "https://github.com/huseyin-aln/005-Sass-Website",
    tool: "css",
  },
  {
    id: 12,
    name: "bootstrap-project",
    image: "bootstrap-project",
    url: "huseyin-aln.github.io/bootstrap-project/",
    source: "https://github.com/huseyin-aln/bootstrap-project",
    tool: "css",
  },
  {
    id: 13,
    name: "Ios-Calculator",
    image: "Ios-Calculator",
    url: "huseyin-aln.github.io/Ios-Calculator/",
    source: "https://github.com/huseyin-aln/Ios-Calculator",
    tool: "javascript",
  },
  {
    id: 14,
    name: "checkOutForm",
    image: "checkOutForm",
    url: "huseyin-aln.github.io/checkOutForm/",
    source: "https://github.com/huseyin-aln/checkOutForm",
    tool: "javascript",
  },
  {
    id: 15,
    name: "weatherApp",
    image: "weatherApp",
    url: "https://huseyin-aln.github.io/weatherApp/",
    source: "https://github.com/huseyin-aln/weatherApp",
    tool: "javascript",
  },
  {
    id: 16,
    name: "flagApp",
    image: "flagApp",
    url: "https://huseyin-aln.github.io/flagApp/",
    source: "https://github.com/huseyin-aln/flagApp",
    tool: "javascript",
  },
  {
    id: 17,
    name: "Capstone-Blog-App-D",
    image: "Capstone-Blog-App-D",
    url: "https://github.com/huseyin-aln/Capstone-Blog-App-D",
    source: "https://github.com/huseyin-aln/Capstone-Blog-App-D",
    tool: "django",
  },
  {
    id: 18,
    name: "Practise-Series",
    image: "Practise-Series",
    url: "https://github.com/huseyin-aln/Practise-Series",
    source: "https://github.com/huseyin-aln/Practise-Series",
    tool: "react",
  },
  {
    id: 19,
    name: "P-ImageToText-RP",
    image: "P-ImageToText-RP",
    url: "https://image-to-text-app.netlify.app/",
    source: "https://github.com/huseyin-aln/P-ImageToText-RP",
    tool: "react",
  },
  {
    id: 20,
    name: "Weather-App-D",
    image: "Weather-App-D",
    url: "https://github.com/huseyin-aln/Weather-App-D",
    source: "https://github.com/huseyin-aln/Weather-App-D",
    tool: "django",
  },
  {
    id: 21,
    name: "Blog-App-D",
    image: "Blog-App-D",
    url: "https://github.com/huseyin-aln/Blog-App-D",
    source: "https://github.com/huseyin-aln/Blog-App-D",
    tool: "django",
  },
  {
    id: 22,
    name: "All-Auth-Google-D",
    image: "All-Auth-Google-D",
    url: "https://github.com/huseyin-aln/All-Auth-Google-D",
    source: "https://github.com/huseyin-aln/All-Auth-Google-D",
    tool: "django",
  },
  {
    id: 23,
    name: "Todo-App-Auth-D",
    image: "Todo-App-Auth-D",
    url: "http://benh.pythonanywhere.com/",
    source: "https://github.com/huseyin-aln/Todo-App-Auth-D",
    tool: "django",
  },
  {
    id: 24,
    name: "Pizza-Order-Website-D",
    image: "Pizza-Order-Website-D",
    url: "https://github.com/huseyin-aln/Pizza-Order-Website-D",
    source: "https://github.com/huseyin-aln/Pizza-Order-Website-D",
    tool: "django",
  },
  {
    id: 25,
    name: "Student-Register-D",
    image: "Student-Register-D",
    url: "https://github.com/huseyin-aln/Student-Register-D",
    source: "https://github.com/huseyin-aln/Student-Register-D",
    tool: "django",
  },
  {
    id: 26,
    name: "Create-RandomNumber-RP",
    image: "Create-RandomNumber-RP",
    url: "https://github.com/huseyin-aln/Create-RandomNumber-RP",
    source: "https://github.com/huseyin-aln/Create-RandomNumber-RP",
    tool: "react",
  },
  {
    id: 27,
    name: "Image-Gallery-RP",
    image: "Image-Gallery-RP",
    url: "https://github.com/huseyin-aln/Image-Gallery-RP",
    source: "https://github.com/huseyin-aln/Image-Gallery-RP",
    tool: "react",
  },
  {
    id: 28,
    name: "Image-Gallery-RP",
    image: "Image-Gallery-RP",
    url: "https://github.com/huseyin-aln/Image-Gallery-RP",
    source: "https://github.com/huseyin-aln/Image-Gallery-RP",
    tool: "react",
  },
  {
    id: 29,
    name: "Language-Cards-RP",
    image: "Language-Cards-RP",
    url: "https://language-cards-rp-02.netlify.app/",
    source: "https://github.com/huseyin-aln/Language-Cards-RP-02",
    tool: "react",
  },
  {
    id: 30,
    name: "Contact-List-App-RP",
    image: "Contact-List-App-RP",
    url: "https://contact-list-app-rp.netlify.app/",
    source: "https://github.com/huseyin-aln/Contact-List-App-RP",
    tool: "react",
  },
  {
    id: 31,
    name: "Task-Tracker-RP",
    image: "Task-Tracker-RP",
    url: "https://task-tracker-rp.netlify.app/",
    source: "https://github.com/huseyin-aln/Task-Tracker-RP",
    tool: "react",
  },
  {
    id: 32,
    name: "Axios-Router-RP",
    image: "Axios-Router-RP",
    url: "https://axios-router-example-rp.netlify.app/",
    source: "https://github.com/huseyin-aln/Axios-Router-RP",
    tool: "react",
  },
  {
    id: 33,
    name: "Random-User-RP",
    image: "Random-User-RP",
    url: "https://random-user-rp.netlify.app/",
    source: "https://github.com/huseyin-aln/Random-User-RP",
    tool: "react",
  },
  {
    id: 34,
    name: "Formik-Yup-RP",
    image: "Formik-Yup-RP",
    url: "https://formik-yup-rp.netlify.app/",
    source: "https://github.com/huseyin-aln/Formik-Yup-RP",
    tool: "react",
  },
  {
    id: 35,
    name: "News-App-RP",
    image: "News-App-RP",
    url: "https://github.com/huseyin-aln/News-App-RP",
    source: "https://github.com/huseyin-aln/News-App-RP",
    tool: "react",
  },
  {
    id: 36,
    name: "Country-Holiday-RP",
    image: "Country-Holiday-RP",
    url: "https://github.com/huseyin-aln/Country-Holiday-RP",
    source: "https://github.com/huseyin-aln/Country-Holiday-RP",
    tool: "react",
  },
  {
    id: 37,
    name: "vowelsCounter",
    image: "vowelsCounter",
    url: "https://huseyin-aln.github.io/vowelsCounter/",
    source: "https://github.com/huseyin-aln/vowelsCounter",
    tool: "javascript",
  },
  {
    id: 38,
    name: "randomUser",
    image: "randomUser",
    url: "https://huseyin-aln.github.io/randomUser/",
    source: "https://github.com/huseyin-aln/randomUser",
    tool: "javascript",
  },
  {
    id: 39,
    name: "digitalClock",
    image: "digitalClock",
    url: "https://huseyin-aln.github.io/digitalClock/",
    source: "https://github.com/huseyin-aln/digitalClock",
    tool: "javascript",
  },
  {
    id: 40,
    name: "Guess-The-Number",
    image: "Guess-The-Number",
    url: "https://huseyin-aln.github.io/Guess-The-Number/",
    source: "https://github.com/huseyin-aln/Guess-The-Number",
    tool: "javascript",
  },
  {
    id: 41,
    name: "To-Do-List",
    image: "To-Do-List",
    url: "https://huseyin-aln.github.io/To-Do-List/",
    source: "https://github.com/huseyin-aln/To-Do-List",
    tool: "javascript",
  },
  {
    id: 42,
    name: "checkout-form",
    image: "checkout-form",
    url: "https://huseyin-aln.github.io/checkout-form/",
    source: "https://github.com/huseyin-aln/checkout-form",
    tool: "javascript",
  },
  {
    id: 43,
    name: "navBarExample",
    image: "navBarExample",
    url: "https://huseyin-aln.github.io/navBarExample/",
    source: "https://github.com/huseyin-aln/navBarExample",
    tool: "css",
  },
  {
    id: 44,
    name: "Bootstrap_breakpoints_example-2",
    image: "Bootstrap_breakpoints_example-2",
    url: "https://huseyin-aln.github.io/Bootstrap_breakpoints_example-2/",
    source: "https://github.com/huseyin-aln/Bootstrap_breakpoints_example-2",
    tool: "css",
  },
  {
    id: 45,
    name: "Bootstrap_breakpoints_example-1",
    image: "Bootstrap_breakpoints_example-1",
    url: "https://huseyin-aln.github.io/Bootstrap_breakpoints_example-1/",
    source: "https://github.com/huseyin-aln/Bootstrap_breakpoints_example-1",
    tool: "css",
  },
  {
    id: 46,
    name: "website",
    image: "website",
    url: "https://huseyin-aln.github.io/website/",
    source: "https://github.com/huseyin-aln/website",
    tool: "css",
  },
  {
    id: 47,
    name: "css-grid-calculator",
    image: "css-grid-calculator",
    url: "https://huseyin-aln.github.io/css-grid-calculator/",
    source: "https://github.com/huseyin-aln/css-grid-calculator",
    tool: "css",
  },
  {
    id: 48,
    name: "left-menu",
    image: "left-menu",
    url: "https://huseyin-aln.github.io/left-menu/",
    source: "https://github.com/huseyin-aln/left-menu",
    tool: "css",
  },
  {
    id: 49,
    name: "bgImage",
    image: "bgImage",
    url: "https://huseyin-aln.github.io/bgImage/",
    source: "https://github.com/huseyin-aln/bgImage",
    tool: "css",
  },
  {
    id: 50,
    name: "layout",
    image: "layout",
    url: "https://huseyin-aln.github.io/layout/",
    source: "https://github.com/huseyin-aln/layout",
    tool: "css",
  },
  {
    id: 51,
    name: "popup-menu",
    image: "popup-menu",
    url: "https://huseyin-aln.github.io/popup-menu/",
    source: "https://github.com/huseyin-aln/popup-menu",
    tool: "css",
  },
  {
    id: 52,
    name: "flex-grid",
    image: "flex-grid",
    url: "https://huseyin-aln.github.io/flex-grid/",
    source: "https://github.com/huseyin-aln/flex-grid",
    tool: "css",
  },
  {
    id: 53,
    name: "google-landing-page",
    image: "google-landing-page",
    url: "https://huseyin-aln.github.io/002-google-landing-page/",
    source: "https://github.com/huseyin-aln/002-google-landing-page",
    tool: "css",
  },
  {
    id: 54,
    name: "survey-form",
    image: "survey-form",
    url: "https://huseyin-aln.github.io/002-survey-form/",
    source: "https://github.com/huseyin-aln/002-survey-form",
    tool: "css",
  },
  {
    id: 55,
    name: "shopping-cart",
    image: "shopping-cart",
    url: "https://huseyin-aln.github.io/shopping-cart/",
    source: "https://github.com/huseyin-aln/shopping-cart",
    tool: "css",
  },
  {
    id: 56,
    name: "nav-bar",
    image: "nav-bar",
    url: "https://huseyin-aln.github.io/nav-bar/",
    source: "https://github.com/huseyin-aln/nav-bar",
    tool: "css",
  },
  {
    id: 57,
    name: "leap-year",
    image: "leap-year",
    url: "https://huseyin-aln.github.io/nav-bar/",
    source: "https://github.com/huseyin-aln/leap-year",
    tool: "javascript",
  },
  {
    id: 58,
    name: "survey-form-netflix",
    image: "survey-form-netflix",
    url: "https://huseyin-aln.github.io/001-survey-form-netflix/",
    source: "https://github.com/huseyin-aln/001-survey-form-netflix",
    tool: "css",
  },
  {
    id: 59,
    name: "Calculator",
    image: "Calculator",
    url: "https://huseyin-aln.github.io/Calculator/",
    source: "https://github.com/huseyin-aln/Calculator",
    tool: "javascript",
  },
  {
    id: 60,
    name: "interactive-component",
    image: "interactive-component",
    url: "https://huseyin-aln.github.io/interactive-component/",
    source: "https://github.com/huseyin-aln/interactive-component",
    tool: "javascript",
  },
  {
    id: 61,
    name: "ChangeBgColor",
    image: "ChangeBgColor",
    url: "https://huseyin-aln.github.io/ChangeBgColor/",
    source: "https://github.com/huseyin-aln/ChangeBgColor",
    tool: "javascript",
  },
  {
    id: 62,
    name: "stopwatch",
    image: "stopwatch",
    url: "https://huseyin-aln.github.io/stopwatch/",
    source: "https://github.com/huseyin-aln/stopwatch",
    tool: "javascript",
  },
  {
    id: 63,
    name: "web-page-design",
    image: "web-page-design",
    url: "https://huseyin-aln.github.io/web-page-design/",
    source: "https://github.com/huseyin-aln/web-page-design",
    tool: "css",
  },
  {
    id: 64,
    name: "domEventExample",
    image: "domEventExample",
    url: "https://huseyin-aln.github.io/domEventExample/",
    source: "https://github.com/huseyin-aln/domEventExample",
    tool: "javascript",
  },
  {
    id: 65,
    name: "loanCalculator",
    image: "loanCalculator",
    url: "https://huseyin-aln.github.io/loanCalculator/",
    source: "https://github.com/huseyin-aln/loanCalculator",
    tool: "javascript",
  },
];

export default data;
